<a href="https://colab.research.google.com/github/g9ukxv/PyTorch-Tutorial/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TENSOR MATH OPERATIONS

*   Add, Subtract, Multiple, Divide, Remainders,Exponents
*   Shorthand and uh, Longhand
*   Reassignment




In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [5]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [6]:
# Sub Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [7]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [8]:
# Multiplication Longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [9]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [10]:
# Division Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])